catalog/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^games/$', views.GameListView.as_view(), name='games'),
    url(r'^game/(?P<pk>\d+)$', views.GameDetailView.as_view(), name='game-detail'),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]


# Используйте include() чтобы добавлять URL из каталога приложения 
from django.urls import include
from django.urls import path
urlpatterns += [
     path('catalog/', include('catalog.urls')),
]

# Добавьте URL соотношения, чтобы перенаправить запросы с корневового URL, на URL приложения 
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Используйте static() чтобы добавить соотношения для статических файлов
# Только на период разработки
from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

catalog/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):
    """
    Model representing a game genre.
    """
    name = models.CharField(max_length=200, help_text="Enter a game genre")
    
    def __str__(self):
        """
        String for representing the Model object (in Admin site etc.)
        """
        return self.name
		
		
from django.urls import reverse #Used to generate URLs by reversing the URL patterns

class Game(models.Model):
    """
    Model representing a game.
    """
    title = models.CharField(max_length=200)
    studio = models.ForeignKey('Studio', on_delete=models.SET_NULL, null=True)
    # Foreign Key used because game can only have one studio, but studios can have multiple games
    # Studio as a string rather than object because it hasn't been declared yet in the file.
    summary = models.TextField(max_length=1000, help_text="Enter a brief description of the game")
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this game")
    # ManyToManyField used because genre can contain many games. Games can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    
    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.title
    
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular game instance.
        """
        return reverse('game-detail', args=[str(self.id)])
		

		
		
class Studio(models.Model):
    """
    Model representing a studio.
    """
    first_name = models.CharField(max_length=100)
   
    
    def get_absolute_url(self):
        """
        Returns the url to access a particular studio instance.
        """
        return reverse('studio-detail', args=[str(self.id)])
    

    def __str__(self):
        """
        String for representing the Model object.
        """
        return self.first_name
		

		


	

catalog/views.py
from django.shortcuts import render

# Create your views here.

from .models import Game, Studio, Genre

def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # Генерация "количеств" некоторых главных объектов
    num_games=Game.objects.all().count()    
    num_studios=Studio.objects.count()  # The 'all()' is implied by default.
	
    # Number of visits to this view, as counted in the session variable.
    num_visits=request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits+1
    
 # Render the HTML template index.html with the data in the context variable.
    return render(
        request,
        'index.html',
        context={'num_games':num_games,'num_studios':num_studios,'num_visits':num_visits}, # num_visits appended
    )
	
from django.views import generic

class GameListView(generic.ListView):
    model = Game

	
class GameDetailView(generic.DetailView):
    model = Game

catalog/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
<head>
  
  {% block title %}<title>Games catalog</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  
  <!-- Добавление дополнительного статического CSS файла -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>

  <div class="container-fluid">

    <div class="row">
      <div class="col-sm-2">
      {% block sidebar %}
      <ul class="sidebar-nav">
          <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'games' %}">All games</a></li>
          <li><a href="">All studios</a></li>
      </ul>
     {% endblock %}
      </div>
      <div class="col-sm-10 ">
      {% block content %}{% endblock %}
	  
	  {% block pagination %}
  {% if is_paginated %}
      <div class="pagination">
          <span class="page-links">
              {% if page_obj.has_previous %}
                  <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
              {% endif %}
              <span class="page-current">
                  Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
              </span>
              {% if page_obj.has_next %}
                  <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
              {% endif %}
          </span>
      </div>
  {% endif %}
{% endblock %}
      </div>
    </div>

  </div>
</body>
</html>

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ game.title }}</h1>

  <p><strong>Studio:</strong> <a href="">{{ game.studio }}</a></p> <!-- studio detail link not yet defined -->
  <p><strong>Summary:</strong> {{ game.summary }}</p>
  <p><strong>Language:</strong> {{ game.language }}</p>  
  <p><strong>Genre:</strong> {% for genre in game.genre.all %} {{ genre }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>  

{% endblock %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Game List</h1>

    {% if game_list %}
    <ul>

      {% for game in game_list %}
      <li>
        <a href="{{ game.get_absolute_url }}">{{ game.title }}</a> ({{game.st}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no games in the catalog.</p>
    {% endif %}       
{% endblock %}

catalog/templates/index.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Games catalog Home</h1>

  <p>Welcome to <em>Games catalog</em>, a very basic Django website developed as graduation project.</p>

<h2>Dynamic content</h2>

  <p>The library has the following record counts:</p>
  <ul>
    <li><strong>Games:</strong> {{ num_books }}</li>
    <li><strong>Studios:</strong> {{ num_studios }}</li>
  </ul>
  
<p>You have visited this page {{ num_visits }}{% if num_visits == 1 %} time{% else %} times{% endif %}.</p>

{% endblock %}